SistemaDeVentasV1/Models/Compras.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeVentasV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.DetallesCompra = new HashSet<DetallesCompra>();
        }
    
        public int idCompra { get; set; }
        public int idFactura { get; set; }
        public string idProveedor { get; set; }
        public Nullable<decimal> total { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesCompra> DetallesCompra { get; set; }
    }
}

SistemaDeVentasV1/Models/Detalles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeVentasV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles
    {
        public int idDetalle { get; set; }
        public int idFactura { get; set; }
        public string idProducto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<decimal> descuento { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}

SistemaDeVentasV1/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaDeVentasV1.Models;

namespace SistemaDeVentasV1.Controllers
{
    [Authorize(Roles = "Administrador, Bodega")]
    public class ComprasController : Controller
    {
        private FacturacionDbEntities db = new FacturacionDbEntities();

        // GET: Compras
        public ActionResult Index()
        {
            var compras = db.Compras.Include(c => c.Proveedores);
            return View(compras.ToList());
        }

        // GET: Compras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            //var detallesCompra = db.DetallesCompra.Include(d => d.Compras).Include(d => d.Productos);
            ViewBag.Detalles = db.DetallesCompra.Where(d => d.idCompra == id).ToList();
            if (compras == null)
            {

                var compras2 = db.Compras.Include(c => c.Proveedores);
                ViewBag.Error = "No se ha encontrado la compra con el id indicado, pruebe buscar en la tabla general";
                return View("Index",compras2.ToList());
            }

            return View(compras);
        }

        // GET: Compras/Create
        public ActionResult Create()
        {
            ViewBag.idProveedor = new SelectList(db.Proveedores, "idProveedor", "empresa");
            return View();
        }

        // POST: Compras/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCompra,idFactura,idProveedor,total,fecha,creado,modificado")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                //compras.creado = DateTime.Now;
                compras.modificado = DateTime.Now;
                db.Compras.Add(compras);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idProveedor = new SelectList(db.Proveedores, "idProveedor", "empresa", compras.idProveedor);
            return View(compras);
        }

        // GET: Compras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            ViewBag.idProveedor = new SelectList(db.Proveedores, "idProveedor", "empresa", compras.idProveedor);
            return View(compras);
        }

        // POST: Compras/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCompra,idFactura,idProveedor,total,fecha,creado,modificado")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                compras.modificado = DateTime.Now;
                db.Entry(compras).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idProveedor = new SelectList(db.Proveedores, "idProveedor", "empresa", compras.idProveedor);
            return View(compras);
        }

        // GET: Compras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            return View(compras);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compras compras = db.Compras.Find(id);
            db.Compras.Remove(compras);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaDeVentasV1/Controllers/DetallesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaDeVentasV1.Models;
using SistemaDeVentasV1.Dao;

namespace SistemaDeVentasV1.Controllers
{
    [Authorize(Roles = "Administrador, Ventas")]
    public class DetallesController : Controller
    {
        private FacturacionDbEntities db = new FacturacionDbEntities();
        private IDetallesDao dao = new DetallesDao();

        // GET: Detalles
        public ActionResult Index()
        {
            var detalles = db.Detalles.Include(d => d.Facturas).Include(d => d.Productos);
            return View(detalles.ToList());
        }

        // GET: Detalles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalles detalles = db.Detalles.Find(id);
            if (detalles == null)
            {
                return HttpNotFound();
            }
            return View(detalles);
        }

        // GET: Detalles/Create
        public ActionResult Create()
        {
            ViewBag.idFactura = new SelectList(db.Facturas, "idFactura", "nitCliente");
            ViewBag.idProducto = new SelectList(db.Productos, "idProducto", "nombre");
            return View();
        }

        // POST: Detalles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idDetalle,idFactura,idProducto,cantidad,precio,subTotal")] Detalles detalles)
        {
            if (ModelState.IsValid)
            {
                // db.Detalles.Add(detalles);
                //db.SaveChanges();
                dao.Crear(detalles);
                return RedirectToAction("Index");
            }

            ViewBag.idFactura = new SelectList(db.Facturas, "idFactura", "nitCliente", detalles.idFactura);
            ViewBag.idProducto = new SelectList(db.Productos, "idProducto", "nombre", detalles.idProducto);
            return View(detalles);
        }

        // GET: Detalles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalles detalles = db.Detalles.Find(id);
            if (detalles == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFactura = new SelectList(db.Facturas, "idFactura", "nitCliente", detalles.idFactura);
            ViewBag.idProducto = new SelectList(db.Productos, "idProducto", "nombre", detalles.idProducto);
            return View(detalles);
        }

        // POST: Detalles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idDetalle,idFactura,idProducto,cantidad,precio,subTotal")] Detalles detalles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detalles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idFactura = new SelectList(db.Facturas, "idFactura", "nitCliente", detalles.idFactura);
            ViewBag.idProducto = new SelectList(db.Productos, "idProducto", "nombre", detalles.idProducto);
            return View(detalles);
        }

        // GET: Detalles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalles detalles = db.Detalles.Find(id);
            if (detalles == null)
            {
                return HttpNotFound();
            }
            return View(detalles);
        }

        // POST: Detalles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Detalles detalles = db.Detalles.Find(id);
            db.Detalles.Remove(detalles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaDeVentasV1/Views/Compras/Create.cshtml
@model SistemaDeVentasV1.Models.Compras

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compras</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idFactura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idProveedor, "idProveedor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idProveedor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="fecha" id="fecha" value="@DateTime.Now" required class="form-control" />
               
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaDeVentasV1/Views/Compras/Delete.cshtml
@model SistemaDeVentasV1.Models.Compras

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compras</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idFactura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFactura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modificado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proveedores.empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proveedores.empresa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SistemaDeVentasV1/Views/Compras/Details.cshtml
@model SistemaDeVentasV1.Models.Compras

@{
    ViewBag.Title = "Detalle de Compras";
    ViewBag.TituloControlador = "COMPRAS";
    ViewBag.InfoPagina = "Informacion de Compras";
    ViewBag.TituloVentana = "Datos de compras ingresadas al sistema";
    ViewBag.FooterVentana = "Despues de ingresar una compra al sistema esta no se puede modificar, para garantizar la integridad de los datos";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-2">
                <label>Id Compra: </label> <ins>@Html.DisplayFor(model => model.idCompra)</ins>
            </div>
            <div class="col-md-2">
                <label>Id Factura: </label> <ins>@Html.DisplayFor(model => model.idFactura)</ins>
            </div>
            <div class="col-md-3">
                <label>Fecha: </label> <ins>@Html.DisplayFor(model => model.fecha)</ins>
            </div>
            <div class="col-md-3">
                <label>Total: </label> <ins>Q @Html.DisplayFor(model => model.total)   </ins>
            
            </div>
           
           
        </div>
        <div class="row">
            <div class="col-md-3">
                <label>Proveedor: </label> <ins>@Html.DisplayFor(model => model.Proveedores.empresa)</ins>
            </div>
            <div class="col-md-3">
                <label>Contacto: </label> <ins>@Html.DisplayFor(model => model.Proveedores.nombre)</ins>
            </div>
            <div class="col-md-3">
                <label>Tel.: </label> <ins>@Html.DisplayFor(model => model.Proveedores.telefono)</ins>
            </div>
            <div class="col-d=md-3">
                <label>Ingreso compra: </label> <ins>        </ins>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_Detalles")
    </div> 
</div>
<div class="row">
    <div class="col-md-9">

    </div>
    <div class="col-md-3">
        <label>Total Q.</label> @Html.DisplayFor(model => model.total)
    </div>
</div>
<div class="row">
    <p>
        <input type="button" disabled class="btn btn-info" value="Actualizar Registro" onclick="location.href='@Url.Action("Edit", "Facturas", new {id = Model.idFactura })'" /> |
        <input type="button" disabled class="btn btn-danger" value="Eliminar Registro" onclick="location.href='@Url.Action("Delete", "Facturas", new {id = Model.idFactura })'" /> |
        <a href="@Url.Action("Index","Compras")" class="btn btn-success">Regresar a la lista</a>
    </p>
</div>

SistemaDeVentasV1/Views/Compras/Edit.cshtml
@model SistemaDeVentasV1.Models.Compras

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compras</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idCompra)

        <div class="form-group">
            @Html.LabelFor(model => model.idFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idFactura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idProveedor, "idProveedor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idProveedor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.creado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.creado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.creado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modificado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modificado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modificado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaDeVentasV1/Views/Compras/Index.cshtml
@model IEnumerable<SistemaDeVentasV1.Models.Compras>

@{
    ViewBag.Title = "Compras Registradas";
    ViewBag.TituloControlador = "COMPRAS";
    ViewBag.InfoPagina = "Compras Registradas en el sistema";
    ViewBag.TituloVentana = "Lista de compras realizadas";
    ViewBag.FooterVentana = "Para ver el detalle completo de la compra, click en el boton Ver detalles";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            @Html.ActionLink("Create","Create")
            <a href="@Url.Action("IgresarCompra","IngresoMercaderia")" class="btn btn-primary" role="button">Ingresar Compra</a>
        </div>
        <div class="col-md-8">
            <form id="fBuscarId" action="Details" method="get" class="form-inline">
                <div class="form-group">
                    <label>No. Compra</label>
                    <input type="number" min="1" size="6" name="id" id="id" required class="form-control" />
                    <input type="submit" name="btnBuscar" value="Buscar" class="btn btn-info" />
                </div>
            </form>
        </div>
    </div>
</div>
<p>

</p>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idFactura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.modificado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proveedores.empresa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idFactura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.modificado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Proveedores.empresa)
                </td>
                <td>
                    <form id="fDetalles" action="Details" method="get">
                        <input type="hidden" id="id" name="id" value="@item.idFactura" />
                        <input type="submit" id="btnDetalles" value="Ver Detalles" formaction="Details" class="btn btn-info" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    <script>
            $(document).ready(function () {
                $('#example1').DataTable({
                    "language": {

                        "sProcessing": "Procesando...",

                        "sLengthMenu": "Mostrar _MENU_ registros",

                        "sZeroRecords": "No se encontraron resultados",

                        "sEmptyTable": "Ningún dato disponible en esta tabla",

                        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",

                        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",

                        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",

                        "sInfoPostFix": "",

                        "sSearch": "Buscar:",

                        "sUrl": "",

                        "sInfoThousands": ",",

                        "sLoadingRecords": "Cargando...",

                        "oPaginate": {

                            "sFirst": "Primero",

                            "sLast": "Último",

                            "sNext": "Siguiente",

                            "sPrevious": "Anterior"

                        },

                        "oAria": {

                            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",

                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"

                        }

                    }
                });
            });
    </script>
}

SistemaDeVentasV1/Views/Compras/_Detalles.cshtml
@using SistemaDeVentasV1.Models;

@{ 
    List<DetallesCompra> detalles = new List<DetallesCompra>();
    if (ViewBag.Detalles ==null)
    {

    }
    else
    {
        detalles = (List<DetallesCompra>)ViewBag.Detalles;
    }
}
<center><h3 class="h3">Detalles de la Compra</h3></center>
<table class="table table-bordered table-responsive table-striped">
    <thead>
        <tr>
            <th>
                Id 
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Producto
            </th>
            <th>
               Precio
            </th>
            <th>
               SubTotal
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in detalles)
        {
            <tr>
                <td>
                   @item.idDetalle
                </td>
                <td>
                    @item.cantidad
                </td>
                <td>
                    @item.idProducto , @item.Productos.nombre
                </td>
                <td>
                   Q. @item.precio
                </td>
                <td>
                    Q. @item.subTotal
                </td>
                
            </tr>
        }
    </tbody>
</table>