SistemaDeVentasV1/Models/Proveedores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeVentasV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public string idProveedor { get; set; }
        public string empresa { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
    }
}

SistemaDeVentasV1/Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaDeVentasV1.Models;

namespace SistemaDeVentasV1.Controllers
{
    [Authorize(Roles = "Administrador, Bodega")]
    public class ProveedoresController : Controller
    {
        private FacturacionDbEntities db = new FacturacionDbEntities();

        // GET: Proveedores
        public ActionResult Index()
        {
            return View(db.Proveedores.ToList());
        }

        // GET: Proveedores/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedores proveedores = db.Proveedores.Find(id);
            if (proveedores == null)
            {
                return HttpNotFound();
            }
            return View(proveedores);
        }

        // GET: Proveedores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProveedor,empresa,nombre,direccion,telefono,email,creado,modificado")] Proveedores proveedores)
        {
      
            if (ModelState.IsValid)
            {
                proveedores.creado = DateTime.Now;
                proveedores.modificado = DateTime.Now;
                db.Proveedores.Add(proveedores);
                db.SaveChanges();
                ViewBag.Mensaje = "Registro Creado";
                return View("Index", db.Proveedores.ToList());
            }
            ViewBag.Error = "No se pudo crear el registro en la base de datos";
            return View(proveedores);
        }

        // GET: Proveedores/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedores proveedores = db.Proveedores.Find(id);
            if (proveedores == null)
            {
                return HttpNotFound();
            }
            return View(proveedores);
        }

        // POST: Proveedores/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idProveedor,empresa,nombre,direccion,telefono,email,creado,modificado")] Proveedores proveedores)
        {
            
            if (ModelState.IsValid)
            {
                proveedores.modificado = DateTime.Now;
                db.Entry(proveedores).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Mensaje = "Registro Actualizado";
                return View("Index", db.Proveedores.ToList());
            }
            ViewBag.Error = "No se pudo actualizar los datos del proveedor";
            return View(proveedores);
        }

        // GET: Proveedores/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedores proveedores = db.Proveedores.Find(id);
            if (proveedores == null)
            {
                return HttpNotFound();
            }
            return View(proveedores);
        }

        // POST: Proveedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {


                Proveedores proveedores = db.Proveedores.Find(id);
                db.Proveedores.Remove(proveedores);
                db.SaveChanges();
                ViewBag.Mensaje = "Se ha eliminado un registro de la base de datos";
                return View("Index", db.Proveedores.ToList());
            }
            catch
            {
                ViewBag.Error = "No se pudo elimianar el registro";
                return View(id);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaDeVentasV1/Views/Proveedores/Create.cshtml
@model SistemaDeVentasV1.Models.Proveedores

@{
    ViewBag.Title = "Create";
    ViewBag.TituloControlador = "PROVEEDORES";
    ViewBag.InfoPagina = "Registro de un nuevo proveedor al sistema";
    ViewBag.TituloVentana = "Registro de Proveedores";
    ViewBag.FooterVentana = "Todos los datos son requeridos para mejor control del sistema.";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}
<div class="row">
    <div class="co-md-12">
        <div class="col-md-8">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                 
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.idProveedor, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idProveedor, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                            @Html.ValidationMessageFor(model => model.idProveedor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.empresa, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.empresa, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                            @Html.ValidationMessageFor(model => model.empresa, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                            @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>                          
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Crear Registro" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>
<div class="row">
    <a href="@Url.Action("Index","Proveedores")" class="btn btn-success">Regresar a la lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaDeVentasV1/Views/Proveedores/Delete.cshtml
@model SistemaDeVentasV1.Models.Proveedores

@{
    ViewBag.Title = "Eliminar Proveedor";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
    ViewBag.TituloControlador = "PROVEEDORES";
    ViewBag.InfoPagina = "Eliminar Registro de Proveedores";
    ViewBag.TituloVentana = "Informacion a eliminar";
    ViewBag.FooterVentana = "Puede que la base de datos no le permita eliminar el regisro, de ser asi, contacte con el tecnico";
}
<h3>En realidad desea eliminar el Registro?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idProveedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idProveedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modificado)
        </dd>
    </dl>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            <input type="button" class="btn btn-info" value="Editar Registro" onclick="location.href='@Url.Action("Edit", "Proveedores", new {id = Model.idProveedor })'" /> |
            <a href="@Url.Action("Index","Proveedores")" class="btn btn-success">Regresar a la lista</a>
        </div>
    }
</div>

SistemaDeVentasV1/Views/Proveedores/Details.cshtml
@model SistemaDeVentasV1.Models.Proveedores
@{
    ViewBag.Title = "Info Proveedor";
    ViewBag.TituloControlador = "PROVEEDORES";
    ViewBag.InfoPagina = "Informacion registrada del proveedor";
    ViewBag.TituloVentana = "Datos del Proveedor";
    ViewBag.FooterVentana = "Puede editar y actualizar este registro, click en el boton editar";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idProveedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idProveedor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modificado)
        </dd>

    </dl>
</div>
<p>
    <input type="button" class="btn btn-info" value="Actualizar Registro" onclick="location.href='@Url.Action("Edit", "Proveedores", new {id = Model.idProveedor })'" /> |
    <input type="button" class="btn btn-danger" value="Eliminar Registro" onclick="location.href='@Url.Action("Delete", "Proveedores", new {id = Model.idProveedor })'" /> |
    <a href="@Url.Action("Index","Proveedores")" class="btn btn-success">Regresar a la lista</a>
</p>

SistemaDeVentasV1/Views/Proveedores/Edit.cshtml
@model SistemaDeVentasV1.Models.Proveedores

@{
    ViewBag.Title = "Editar Proveedor";
    ViewBag.TituloControlador = "PROVEEDORES";
    ViewBag.InfoPagina = "Edite los datos del proveedor";
    ViewBag.TituloVentana = "Modifique solo los datos que desea actualizar";
    ViewBag.FooterVentana = "Todos los datos son requeridos ene el sistema";
    Layout = "~/Views/Shared/Plantilla1.cshtml";
}
<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idProveedor)
                <div class="form-group">
                    @Html.LabelFor(model => model.idProveedor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.idProveedor, new { htmlAttributes = new { @class = "form-control", @readonly ="true" } })
                        @Html.ValidationMessageFor(model => model.idProveedor, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.empresa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.empresa, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.empresa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-12">
                        <input type="submit" value="Actualizar datos" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="row">
    <input type="button" class="btn btn-danger" value="Eliminar Registro" onclick="location.href='@Url.Action("Delete", "Proveedores", new {id = Model.idProveedor })'" /> |
    <a href="@Url.Action("Index","Proveedores")" class="btn btn-success">Regresar a la lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaDeVentasV1/Views/Proveedores/Index.cshtml
@model IEnumerable<SistemaDeVentasV1.Models.Proveedores>

@{
    ViewBag.Title = "Listado de Proveedores";
    ViewBag.TituloControlador = "PROVEEDORES";
    ViewBag.InfoPagina = "Proveedores Registrados en el sistema";
    ViewBag.TituloVentana = "Listado de Proveedores Registrados";
    ViewBag.FooterVentana = "Esta tabla muestra el registro de todos los proveedores de quienes se ha comprado mercaderia";

    Layout = "~/Views/Shared/Plantilla1.cshtml";
}
<p>
   
    <a href="@Url.Action("Create","Proveedores")" class="btn btn-primary" role="button">Crear Nuevo</a>
</p>
<table class="table table-bordered table-responsive" id="tProveedores">
    <thead>
        <tr>
            <th>
                Empresa
            </th>
            <th>
                Contacto
            </th>
            <th>
                Direccion
            </th>
            <th>
                Telefono
            </th>
            <th>
                Email
            </th>


            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.empresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
               

                <td>
                    <input type="button" class="btn btn-info" value="Detalles" onclick="location.href='@Url.Action("Details", "Proveedores", new {id = item.idProveedor})'" /> 
                </td>
            </tr>

        }
    </tbody>
</table>


@section scripts{
    <script>
        $(document).ready(function () {
            $('#tProveedores').DataTable({
                "language": {

                    "sProcessing": "Procesando...",

                    "sLengthMenu": "Mostrar _MENU_ registros",

                    "sZeroRecords": "No se encontraron resultados",

                    "sEmptyTable": "Ningún dato disponible en esta tabla",

                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",

                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",

                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",

                    "sInfoPostFix": "",

                    "sSearch": "Buscar:",

                    "sUrl": "",

                    "sInfoThousands": ",",

                    "sLoadingRecords": "Cargando...",

                    "oPaginate": {

                        "sFirst": "Primero",

                        "sLast": "Último",

                        "sNext": "Siguiente",

                        "sPrevious": "Anterior"

                    },

                    "oAria": {

                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",

                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
</script>

   
}